name: E2E Daily Test Runner

on:
  workflow_dispatch:

env:
  C8Y_TENANT: ${{ vars.C8Y_TENANT }}
  C8Y_USERNAME: ${{ vars.C8Y_USERNAME }}
  C8Y_PASSWORD: ${{ secrets.C8Y_PASSWORD }}
  C8Y_BASEURL: ${{ vars.C8Y_BASEURL }}
  C8Y_SHELL_TARGET: 'administration'
  C8Y_CYPRESS_URL: 'http://localhost:4200'

permissions:
  contents: read

jobs: 
  build-plugin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Reminder Plugin
        run: npm run build:reminder

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: reminder-plugin
          if-no-files-found: error
          retention-days: 5
          path: |
            dist/cumulocity-reminder-plugin/**

  test-component:
    runs-on: ubuntu-latest
    needs: build-plugin
    environment: e2e
    name: E2E Test Reminder Plugin
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: reminder-plugin
          path: dist/apps/cumulocity-reminder-plugin/

      - name: Get shell app of particular version
        uses: Cumulocity-IoT/plugins-e2e-setup/get-shell-app@main # reference to get-shell-app action
        with:
          shell-name: cockpit
          shell-version: y2026-lts
          shell-path: dist/apps

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          start: npm run cypress:ctrl # using cumulocity-cypress-control package to host dist folder
          install: false
          wait-on: 'http://localhost:4200/apps/cockpit/index.html?remotes=%7B"sag-pkg-community-plugins"%3A%5B"ExampleWidgetPluginModule"%2C"DatapointsGraphWidgetModule"%5D%7D#'
          browser: chrome
          config-file: cypress.config.ts
